apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-srv
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: bird-of-hermes
    role: web
  ports:
    - name: http
      port: 8000
      targetPort: flask-port
  type: LoadBalancer
